name: CI
permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  argos:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - run: DEBUG=@argos-ci/core npx @argos-ci/cli upload ./screenshots
        env:
          ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
